---
# Source: exadeploy/templates/exadeploy-serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: exadeploy
  namespace: default
  labels:
    helm.sh/chart: exadeploy-1.1.0
    app.kubernetes.io/name: exadeploy
    app.kubernetes.io/instance: exadeploy
    app.kubernetes.io/version: "0.10.0"
    app.kubernetes.io/managed-by: Helm
