{
 "title": "Exafunction Cluster Monitoring",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "runner_name", "label": "Runner Name", "query": "runner-example" },
   { "name": "scheduler_name", "label": "Scheduler Name", "query": "scheduler-example" },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "auto : $__rate_interval,30s,1m,3m,5m,10m"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Exafunction GPU runners (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(group by (kubernetes_pod_name) (grpc_server_handled_total{grpc_service=\"exa.runner_pb.Runner\", kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})) OR on() vector(0)",
     "legendFormat": "Number of Exafunction runners"
    }
   ]
  },
  {
   "title": "Average Module Server Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(module_server_exec_time[${rate_interval}])) OR on() vector(0)\n",
     "legendFormat": "Exec Time (s)"
    },
    {
     "expr": "avg(rate(module_server_exec_lock_time[${rate_interval}])) OR on() vector(0)\n",
     "legendFormat": "Exec Lock Time (s)"
    },
    {
     "expr": "avg(rate(module_server_map_data_time[${rate_interval}])) OR on() vector(0)",
     "legendFormat": "Map Data Time (s)"
    },
    {
     "expr": "avg(rate(module_server_allocate_time[${rate_interval}])) OR on() vector(0)",
     "legendFormat": "Allocate Time (s)"
    },
    {
     "expr": "min(rate(module_server_exec_time[${rate_interval}])) OR on() vector(0)\n",
     "legendFormat": "Min Exec Time (s)"
    }
   ]
  },
  {
   "title": "Average Runner Utilization (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(runner_cpu_utilization{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(value_store_cpu_utilization{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "Value Store CPU"
    },
    {
     "expr": "avg(runner_process_cpu_utilization{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "Runner Process CPU"
    },
    {
     "expr": "avg(runner_gpu_utilization{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "GPU"
    },
    {
     "expr": "100.0 * sum(runner_gpu_used_memory{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}) / sum(runner_gpu_total_memory{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "GPU Memory"
    }
   ]
  },
  {
   "title": "Average Runner GPU Bandwidth (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(value_store_bytes_transferred_to_gpu{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}[${rate_interval}])) / 1e9 OR on() vector(0)\n",
     "legendFormat": "Total Transferred to GPU (GB/s)"
    },
    {
     "expr": "avg(rate(value_store_bytes_transferred_from_gpu{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}[${rate_interval}])) / 1e9 OR on() vector(0)\n",
     "legendFormat": "Total Transferred from GPU (GB/s)"
    }
   ]
  },
  {
   "title": "Overall Method Run Throughput (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=\"RunMethod\",kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}[${rate_interval}])) OR on() vector(0)",
     "legendFormat": "Method calls per second"
    }
   ]
  },
  {
   "title": "Placement Group Load Time (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(grpc_server_handling_seconds_sum{grpc_method=\"LoadPlacementGroup\", kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"})",
     "legendFormat": "Load latency"
    }
   ]
  },
  {
   "title": "Average Runner Network Bandwidth (use runner name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(value_store_bytes_received{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}[${rate_interval}])) / 1e6 OR on() vector(0)",
     "legendFormat": "Total Receive Bandwidth (MB/s)"
    },
    {
     "expr": "avg(rate(value_store_bytes_sent{kubernetes_pod_name=~\"[[runner_name]]-[0-9]{20}\"}[${rate_interval}])) / 1e6 OR on() vector(0)",
     "legendFormat": "Total Send Bandwidth (MB/s)"
    }
   ]
  },
  {
   "title": "Average Module repository Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_bytes_received_total{grpc_service=\"exa.module_repository_pb.ModuleRepository\"}[${rate_interval}])) / 1e6 OR on() vector(0)",
     "legendFormat": "Total Receive Bandwidth (MB/s)"
    },
    {
     "expr": "sum(rate(grpc_server_bytes_sent_total{grpc_service=\"exa.module_repository_pb.ModuleRepository\"}[${rate_interval}])) / 1e6 OR on() vector(0)",
     "legendFormat": "Total Send Bandwidth (MB/s)"
    }
   ]
  },
  {
   "title": "Scheduler CPU Utilization (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "SUM(scheduler_cpu_utilization{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"})",
     "legendFormat": "Scheduler CPU Utilization"
    },
    {}
   ]
  },
  {
   "title": "Scheduler Memory Usage (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "SUM(scheduler_memory_usage{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) / 1e9",
     "legendFormat": "Scheduler Memory Usage (GB)"
    }
   ]
  },
  {
   "title": "Scheduler Stats (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "SUM(scheduler_created_sessions{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) OR on() vector(0)",
     "legendFormat": "Created sessions"
    },
    {
     "expr": "SUM(scheduler_pending_sessions{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) OR on() vector(0)",
     "legendFormat": "Pending sessions"
    },
    {
     "expr": "SUM(scheduler_created_runners{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) OR on() vector(0)",
     "legendFormat": "Created runners"
    },
    {
     "expr": "SUM(scheduler_pending_runners{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) OR on() vector(0)",
     "legendFormat": "Pending runners"
    }
   ]
  },
  {
   "title": "Scheduler Processing Time (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_processing_time{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}[${rate_interval}])) OR on() vector(0)",
     "legendFormat": "Scheduler Processing Time"
    }
   ]
  },
  {
   "title": "Scheduler Pod Creation Time (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(scheduler_runner_pod_creation_seconds_bucket{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}[${rate_interval}]))",
     "legendFormat": "p50 (s)"
    },
    {
     "expr": "histogram_quantile(0.95, rate(scheduler_runner_pod_creation_seconds_bucket{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}[${rate_interval}]))",
     "legendFormat": "p95 (s)"
    }
   ]
  },
  {
   "title": "Scheduler Invocations (use scheduler name filter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_invocations{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}[${rate_interval}])) OR on() vector(0)",
     "legendFormat": "Scheduler Invocations"
    },
    {
     "expr": "sum(scheduler_requests_queued{kubernetes_pod_name=~\"[[scheduler_name]]-[a-z0-9]+-[a-z0-9]+\"}) OR on() vector(0)",
     "legendFormat": "Requests queued"
    }
   ]
  }
 ]
}