{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "exadeploy.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exadeploy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "exadeploy.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "exadeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
