{{ if .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "exadeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exadeploy.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- .Values.serviceAccount.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
