{{ if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "exadeploy.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exadeploy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs:
  - create
  - get
  - list
  - delete
{{- if .Values.runner.ingress.enabled }}
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete"]
{{- end }}
{{- end }}
