apiVersion: v1
kind: ConfigMap
metadata:
  name: exafunction-config{{- include "exadeploy.suffix" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "exadeploy.labels" . | nindent 4 }}
data:
  exafunction_config.pbtxt: |+
    {{- include "exadeploy.configmap" . | nindent 4 }}
