apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-repository{{- include "exadeploy.suffix" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: module-repository{{- include "exadeploy.suffix" . }}
    {{- include "exadeploy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-repository{{- include "exadeploy.suffix" . }}
  template:
    metadata:
      labels:
        app: module-repository{{- include "exadeploy.suffix" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/exafunction-configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
        {{- if .Values.exafunction.annotations }}
        {{- toYaml .Values.exafunction.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.moduleRepository.serviceAccountName | default (include "exadeploy.serviceAccountName" .) | quote }}
      {{- if .Values.moduleRepository.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.moduleRepository.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.moduleRepository.tolerations }}
      tolerations:
      {{- toYaml .Values.moduleRepository.tolerations | nindent 6 }}
      {{- end }}
      containers:
      - name: module-repository
        image: {{ required "A valid moduleRepository.image is required." .Values.moduleRepository.image }}
        args : [
          "-config=/etc/config/exafunction_config.pbtxt",
        ]
        ports:
        - containerPort: {{ .Values.moduleRepository.port }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.prometheus.port }}
          protocol: TCP
        {{- if .Values.moduleRepository.resources }}
        resources:
          {{- toYaml .Values.moduleRepository.resources | nindent 10 }}
        {{- end }}
        {{- if eq .Values.moduleRepository.backend.type "remote" }}
        env:
        {{- if eq .Values.moduleRepository.backend.remote.dataBackend "s3"}}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ required "A valid moduleRepository.backend.remote.s3.awsAccessKeySecret.name is required." .Values.moduleRepository.backend.remote.s3.awsAccessKeySecret.name | quote }}
              key: {{ required "A valid moduleRepository.backend.remote.s3.awsAccessKeySecret.accessKeyIdKey is required." .Values.moduleRepository.backend.remote.s3.awsAccessKeySecret.accessKeyIdKey | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ required "A valid moduleRepository.backend.remote.s3.awsAccessKeySecret.name is required." .Values.moduleRepository.backend.remote.s3.awsAccessKeySecret.name | quote }}
              key: {{ required "A valid moduleRepository.backend.remote.s3.awsAccessKeySecret.secretAccessKeyKey is required." .Values.moduleRepository.backend.remote.s3.awsAccessKeySecret.secretAccessKeyKey | quote }}
        {{- end }}
        {{- if eq .Values.moduleRepository.backend.remote.dataBackend "gcs"}}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/gcp-credentials.json"
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: "/etc/config"
          readOnly: true
        {{- if eq .Values.moduleRepository.backend.type "remote" }}
        - name: system-secrets
          mountPath: /etc/system_secrets
          readOnly: true
        {{- if .Values.moduleRepository.backend.remote.postgres.sslConfigMapName }}
        - name: ssl-cert
          mountPath: /etc/ssl-cert
          readOnly: true
        {{- end }}
        {{- if eq .Values.moduleRepository.backend.remote.dataBackend "gcs"}}
        - name: gcp-credentials
          mountPath: "/etc/credentials/"
          readOnly: true
        {{- end }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: exafunction-config{{- include "exadeploy.suffix" . }}
      {{- if eq .Values.moduleRepository.backend.type "remote" }}
      - name: system-secrets
        secret:
          secretName: {{ required "A valid moduleRepository.backend.remote.postgres.passwordSecret.name is required." .Values.moduleRepository.backend.remote.postgres.passwordSecret.name | quote }}
          items:
          - key: {{ required "A valid moduleRepository.backend.remote.postgres.passwordSecret.key is required." .Values.moduleRepository.backend.remote.postgres.passwordSecret.key | quote }}
            path: postgres_password
      {{- if .Values.moduleRepository.backend.remote.postgres.sslConfigMapName }}
      - name: ssl-cert
        configMap:
          name: {{ .Values.moduleRepository.backend.remote.postgres.sslConfigMapName }}
      {{- end }}
      {{- if eq .Values.moduleRepository.backend.remote.dataBackend "gcs"}}
      - name: gcp-credentials
        secret:
          secretName: {{ required "A valid moduleRepository.backend.remote.gcs.gcpCredentialsSecret.name is required." .Values.moduleRepository.backend.remote.gcs.gcpCredentialsSecret.name | quote }}
          items:
          - key: {{ required "A valid moduleRepository.backend.remote.gcs.gcpCredentialsSecret.gcpCredentialsJsonKey is required." .Values.moduleRepository.backend.remote.gcs.gcpCredentialsSecret.gcpCredentialsJsonKey | quote }}
            path: gcp-credentials.json
      {{- end }}
      {{- end }}
